### ISSUE TITLE
error in polygonize

### ISSUE THREAD

**Issue by jmigueldelgado** [jmigueldelgado/sar2watermask#22]
```
ERROR 4: No such file or directory
Traceback (most recent call last):
  File "/users/stud09/martinsd/local/miniconda2/envs/gdal/bin/gdal_merge.py", line 540, in <module>
    sys.exit(main())
  File "/users/stud09/martinsd/local/miniconda2/envs/gdal/bin/gdal_merge.py", line 422, in main
    ulx = file_infos[0].ulx
IndexError: list index out of range

 merging mosaics in S1A_IW_GRDH_1SDV_20180214T082616_20180214T082641_020600_02343A_17F9

Traceback (most recent call last):
  File "/users/stud09/martinsd/proj/sar2watermask/polygonize.py", line 29, in <module>
    os.remove(sarOut + "/" + scene + "_*")
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/scratch/martinsd/s1a_scenes/out/S1A_IW_GRDH_1SDV_20180214T082616_2018021\
4T082641_020600_02343A_17F9_*'
```

**Comment by jmigueldelgado** [comment]
not doing merge anymore. problem solved
